namespace BuildingPlanCalc.Services
{
    public static class GlobalVariables
    {
        public enum ShapeTypeEnum
        {
            Line = 1,
            Rect = 2,
            Triangle = 3
        }
        public enum ProjectObjEnum
        {
            ProjectName,
            ManagerName,
            FloorsCount,
            RoomCount,
            BedroomCount,
            KitchensSquare,
            Floor0Height,
            Floor1Height,
            Floor2Height,
            Floor3Height,
            RoofType,
            RoofHeight,
            RoofMinWallHeight,
            RoofSquare,
            RoofLength,
            CanopySquare,
            CanopyLength,
            PergolaSquare,
            HemmingButt,
            HemmingOverhangsSquare,

            Floor0F1GlaseSq,
            Floor0F1GlaseP,
            Floor1F1GlaseSq,
            Floor1F1GlaseP,
            Floor2F1GlaseSq,
            Floor2F1GlaseP,
            Floor3F1GlaseSq,
            Floor3F1GlaseP,

            Floor0F2GlaseSq,
            Floor0F2GlaseP,
            Floor1F2GlaseSq,
            Floor1F2GlaseP,
            Floor2F2GlaseSq,
            Floor2F2GlaseP,
            Floor3F2GlaseSq,
            Floor3F2GlaseP,

            Floor0F3GlaseSq,
            Floor0F3GlaseP,
            Floor1F3GlaseSq,
            Floor1F3GlaseP,
            Floor2F3GlaseSq,
            Floor2F3GlaseP,
            Floor3F3GlaseSq,
            Floor3F3GlaseP,

            Floor0F4GlaseSq,
            Floor0F4GlaseP,
            Floor1F4GlaseSq,
            Floor1F4GlaseP,
            Floor2F4GlaseSq,
            Floor2F4GlaseP,
            Floor3F4GlaseSq,
            Floor3F4GlaseP,

            WindowCount,
            WindowSquare,

            Floor0OutWallsLength,
            Floor0InnerWallsLength,
            Floor0LightWallsLength,
            Floor0BreakWallsLength,
            Floor0Square,
            Floor0OutDoorsCount,
            Floor0OutDoorsLength,
            Floor0InnerDoorsCount,
            Floor0InnerDoorsLength,
            Floor0PartitionsDoorsCount,
            Floor0PartitionsDoorsLength,
            Floor0GatesCount,
            Floor0GatesLength,
            Floor0TerassesSquare,
            Floor0InnerTerassesLength,
            Floor0TerassesLength,
            Floor0RailingsLength,
            Floor0PlinthHeight,
            PlinthOpenPerc,
            Floor0BadroomCount,
            Floor0BadroomSquare,
            Floor0TileSquare,
            Floor0TilePerimeter,

            Floor1OutWallsLength,
            Floor1InnerWallsLength,
            Floor1LightWallsLength,
            Floor1BreakWallsLength,
            Floor1Square,
            Floor1OutDoorsCount,
            Floor1OutDoorsLength,
            Floor1InnerDoorsCount,
            Floor1InnerDoorsLength,
            Floor1PartitionsDoorsCount,
            Floor1PartitionsDoorsLength,
            Floor1GatesCount,
            Floor1GatesLength,
            Floor1TerassesSquare,
            Floor1InnerTerassesLength,
            Floor1TerassesLength,
            Floor1RailingsLength,
            WoodenPillarsLessCount,
            WoodenPillarsOverCount,
            ConcretePillarsLessCount,
            ConcretePillarsOverCount,
            Floor1BadroomCount,
            Floor1BadroomSquare,
            Floor1TileSquare,
            Floor1TilePerimeter,

            Floor2OutWallsLength,
            Floor2InnerWallsLength,
            Floor2LightWallsLength,
            Floor2BreakWallsLength,
            Floor2Square,
            Floor2РHoleSecondLight,
            Floor2OutDoorsCount,
            Floor2OutDoorsLength,
            Floor2InnerDoorsCount,
            Floor2InnerDoorsLength,
            Floor2PartitionsDoorsCount,
            Floor2PartitionsDoorsLength,
            Floor2BalconySquare,
            Floor2BalconyLength,
            Floor2RailingsLength,
            Floor2BadroomCount,
            Floor2BadroomSquare,
            Floor2TileSquare,
            Floor2TilePerimeter,

            Floor3OutWallsLength,
            Floor3InnerWallsLength,
            Floor3LightWallsLength,
            Floor3BreakWallsLength,
            Floor3Square,
            Floor3РHoleSecondLight,
            Floor3OutDoorsCount,
            Floor3OutDoorsLength,
            Floor3InnerDoorsCount,
            Floor3InnerDoorsLength,
            Floor3PartitionsDoorsCount,
            Floor3PartitionsDoorsLength,
            Floor3BalconySquare,
            Floor3BalconyLength,
            Floor3RailingsLength,
            Floor3BadroomCount,
            Floor3BadroomSquare,
            Floor3TileSquare,
            Floor3TilePerimeter

        }
    }
}
